const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    mode: 'jit',
    purge: {
        content: [
            './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.blade.php'
        ],
        safelist: [
            '!block',
            '-left-6',
            'bg-red-100',
            'text-red-600',
            '!text-red-600',
            'bg-green-100',
            'text-green-600',
            '!text-green-600',
            'bg-yellow-100',
            'text-yellow-600',
            '!text-yellow-600',
            'border-blue-500',
            'border-transparent',
            'grid-cols-1',
            'grid-cols-2',
            'grid-cols-3',
            'grid-cols-4',
            'grid-cols-5',
            'grid-cols-6',
            'grid-cols-7',
            'grid-cols-8',
            'grid-cols-9',
            'grid-cols-10',
            'grid-cols-11',
            'grid-cols-12',
            'col-span-1',
            'col-span-2',
            'col-span-3',
            'col-span-4',
            'col-span-5',
            'col-span-6',
            'col-span-7',
            'col-span-8',
            'col-span-9',
            'col-span-10',
            'col-span-11',
            'col-span-12',
            'col-start-1',
            'col-start-2',
            'col-start-3',
            'col-start-4',
            'col-start-5',
            'col-start-6',
            'col-start-7',
            'col-start-8',
            'col-start-9',
            'col-start-10',
            'col-start-11',
            'col-start-12',
            'col-start-13',
            'col-end-1',
            'col-end-2',
            'col-end-3',
            'col-end-4',
            'col-end-5',
            'col-end-6',
            'col-end-7',
            'col-end-8',
            'col-end-9',
            'col-end-10',
            'col-end-11',
            'col-end-12',
            'col-end-13',
            'grid-flow-row',
            'grid-flow-col',
            'justify-around'
        ]
    },

    theme: {
        extend: {
            fontFamily: {
                sans: ['Lato', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    variants: {
        extend: {
            opacity: ['disabled'],
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
